fieldLayouts:
  e09ff03b-1082-4165-aaf8-8868736e28a8:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: cc7a7777-17c5-45ef-829d-9b277cb85134
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Page
        sortOrder: 1
      -
        elements:
          -
            fieldUid: dfb201c1-5d86-40c2-8ef8-8a447a607828
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fe83906d-6f96-4f77-9151-41326628a78d
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1abe3543-0a12-4298-ad7d-1a93ca2d280c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: privacyPolicy
hasTitleField: false
name: 'Privacy Policy'
section: 05857c3a-0daf-412c-a320-780824b26ff5
sortOrder: 1
titleFormat: '{section.name|raw}'
