contentColumnType: string
fieldGroup: dfe9b0d4-736b-4fbd-a584-88932d8d56a9
handle: aspectRatio
instructions: ''
name: 'Aspect Ratio'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - 1-1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Original
        -
          - value
          - original
        -
          - default
          - ''
    -
      __assoc__:
        -
          - optgroup
          - Landscape
    -
      __assoc__:
        -
          - label
          - '16:9'
        -
          - value
          - 16-9
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '5:4'
        -
          - value
          - 5-4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '7:5'
        -
          - value
          - 7-5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4:3'
        -
          - value
          - 4-3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '5:3'
        -
          - value
          - 5-3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6:4'
        -
          - value
          - 6-4
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - optgroup
          - Portrait
    -
      __assoc__:
        -
          - label
          - '9:16'
        -
          - value
          - 9-16
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4-5
        -
          - value
          - 4-5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '5:7'
        -
          - value
          - 5-7
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3:4'
        -
          - value
          - 3-4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3:5'
        -
          - value
          - 3-5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '4:6'
        -
          - value
          - 4-6
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
