contentColumnType: boolean
fieldGroup: 04b3b4bb-5a04-4d55-a1fc-39e4312e4e96
handle: isOngoing
instructions: ''
name: 'Is Ongoing'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
