contentColumnType: text
fieldGroup: dfe9b0d4-736b-4fbd-a584-88932d8d56a9
handle: phoneNumber
instructions: ''
name: 'Phone Number'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
