contentColumnType: text
fieldGroup: dfe9b0d4-736b-4fbd-a584-88932d8d56a9
handle: previewVideo
instructions: ''
name: 'Preview Video'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
